### PR TITLE
Migrating to Bun for Speed and Performance

### PR DESCRIPTION
**Pull request by Wuemeli**
Hey there, I migrated the code to Bun for a faster experience. Unfortunately, Bun doesn't support building, but everything works. Bun is an NPM/Node.js alternative built on top of this. This means you can still use Node.js, etc. If you want, I can migrate the code to https://wails.io/. It's much faster and would support Bun. The code would eventually be faster, etc.

### CODE REVIEW

**Comment by Wuemeli** [comment]
I forgot I also made the .gitignore with all the Node etc. stuff

**Comment by Wuemeli** [comment]
With Migrate all the Code I meant changing readme, package.json, etc

**Comment by hmlendea** [comment]
Is there any way to make it buildable?
It's kind of required, since we need it to distribute it on FlatHub (flatpak is the main format for this app)

**Comment by Wuemeli** [comment]
Sadly, bun doesn't support electron. I could recode the code to another similar Electron alternative.

**Comment by Wuemeli** [comment]
I would need to find a good alternative. I could do that

**Pull request closed without merging**
