### PR TITLE
Updated Electron to 18.2.0 for Steam Deck support.

### PR DESCRIPTION
**Pull request by ilovespicynoodles**
Updating Electron to 18.2.0 did indeed fix the Steam Deck controller not working. I tested it and it works perfect now.

### CODE REVIEW

**Comment by hmlendea** [comment]
Thanks, this is great news!

Could you also please update the `version` value to `1.6.0` and then also run `npm install` again so that the lock-file is updated with the new version?

**Comment by ilovespicynoodles** [comment]
> Thanks, this is great news!
> 
> Could you also please update the `version` value to `1.6.0` and then also run `npm install` again so that the lock-file is updated with the new version?

Sure thing! I will do it when i wake up in the morning 😊

**Comment by ilovespicynoodles** [comment]
I updated the version value to 1.6.0 and ran `npm update`. It should be good to go now :)

**Review by hmlendea — APPROVED** [review]

**Comment by hmlendea** [comment]
Merged, thanks for the contribution!

**Pull request merged**
